#-------------------------------
# General Site Settings
url: "https://great-north-fertility.github.io"
baseurl: "/greatnorthfertility.github.io"
repository:
title: "Great North Fertility" # the name of your site, e.g. ACME Corp.
description: "Bespoke fertility care in Newcastle"

#-------------------------------
# Build settings
markdown: kramdown

permalink: /:title
plugins:
  - jekyll-sitemap

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  style: compressed


#-------------------------------
