#-------------------------------
# General Site Settings
url: "https://greatnorthfertility.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
repository: great-north-fertility/greatnorthfertility.github.io
title: "Great North Fertility" # the name of your site, e.g. ACME Corp.
description: "Bespoke fertility care in Newcastle"

#-------------------------------
# Build settings
markdown: kramdown

permalink: /:title
plugins:
  - jekyll-sitemap

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  style: compressed


#-------------------------------